IronCoreLabs/ironoxide

src/document.rs
src/internal/document_api/mod.rs

This is because recrypt's `decrypt` does not require a mutable reference.

Decrypt no longer requires a mutable self reference

---

.travis.yml
src/document.rs
src/internal/document_api/mod.rs
src/internal/document_api/requests.rs
src/internal/group_api/mod.rs
src/internal/mod.rs
src/internal/rest.rs
src/internal/user_api/mod.rs
src/lib.rs
src/policy.rs
src/prelude.rs
src/user.rs
tests/common/mod.rs
tests/document_ops.rs

Encrypt a document via a server side policy!
This feature can be used to take the burden off the caller to assemble the correct set of users and groups that need access to the document. A policy is identified by the triple (Category, Sensitivity, Data Subject) and is stored in the IronCore web service. Given values for the triple, the policy can be evaluated to get the correct set of users and groups from the web service during an encrypt operation.
Policy-based encryption can also be combined with explicit grants.
Read more about policy in policy.rs

[#15] Encrypt via policy

---

src/internal/document_api/requests.rs
src/internal/user_api/mod.rs
src/policy.rs
tests/common/mod.rs
tests/document_ops.rs

...and make string values of PolicyGrant components available to the outside world

Remove type SubstituteId 

---

.gitignore
src/document/advanced.rs
src/document/mod.rs
src/internal/document_api/mod.rs
src/internal/document_api/requests.rs
src/internal/group_api/mod.rs
src/internal/mod.rs
src/internal/rest.rs
tests/document_ops.rs

see #22 
`DocumentAdvancedOps::document_decrypt_unmanaged` function added for advanced use cases. This decrypt operation is the inverse of `DocumentAdvancedOps::document_encrypt_unmanaged`

[#22] Unmanaged Decryption

---

CHANGELOG.md
Cargo.toml
src/internal/mod.rs
src/internal/user_api/mod.rs
src/internal/user_api/requests.rs
src/user.rs

Needed some changes for ironoxide-java/ironoxide-scala
- Added `impl TryFrom<&[u8]> for PublicKey`
- Added test for it
- Updated the Changelog for version 0.11.0

Add TryFrom to PublicKey

---

CHANGELOG.md
Cargo.toml
src/crypto/aes.rs
src/document/advanced.rs
src/document/mod.rs
src/group.rs
src/internal/document_api/mod.rs
src/internal/document_api/requests.rs
src/internal/group_api/mod.rs
src/internal/group_api/requests.rs
src/internal/mod.rs
src/internal/user_api/mod.rs
src/lib.rs
tests/common/mod.rs
tests/document_ops.rs
tests/user_ops.rs

- Changed DeviceContext::new to take a device_id, renamed some parameters
- Flattened serialization of RequestAuth for DeviceContext
- Added test that serialization of DeviceContext matches new format
TODO:

Change DeviceContext parameters/serialization

---

CHANGELOG.md
Cargo.toml
src/internal/group_api/mod.rs
src/internal/group_api/requests.rs
tests/group_ops.rs

- Added needs_rotation as an `Option<bool>` to:
- `GroupMetaResult`
- `GroupGetResult`
- `GroupBasicApiResponse`
- `GroupGetApiResponse`
- `GroupListResult` is simply a `Vec<GroupMetaResult>`, so it will get these changes.
- Added a test for `group_get_metadata()` that tests a call by an admin, member, and non-member.
`needs_rotation` will be a `None` for a non-admin, and a `Some` for an admin.

Add needs_rotation to group responses

---

build.rs
src/lib.rs
src/proto/mod.rs

Should address #55 
rust-protobuf's documentation shows putting generated code directly into the project's `src/` directory. cargo has always discouraged writing to `src/`as part of the build process, but now docs.rs's sandboxing is actually enforcing this.
Various codegen examples show using the `include!` macro to bring generated code in from the cargo `OUT_DIR`, but the code that rust-protobuf generates isn't really compatible with that approach as it has some top-level `allow` macros that are "out of place" when brought in with the `include` trick.
The solution I've implemented is to wrap the generated code in a module. It's not pretty but I came across a couple of places doing the [same](https://hclarke.ca/generated-code-in-rust.html) …

[#55] Moves generated code from transform.proto into the rust OUT_DIR

---

RELEASING.md

see #61 
This is my proposal for what we should do for releases. 
In short
* change log entries are added during the PR process for individual changes
* the version number will be changed at part of the PR process, if needed. If a previous PR has already bumpd the minor version number, subsequent PRs don't need to change the version number.
* `git tag -a` should be used to tag the release with the current release's change log entry as the commit message. This commit message will appear on github releases.

[#61] Update release process

---

CHANGELOG.md
Cargo.toml
src/group.rs
src/internal/group_api/mod.rs
src/internal/group_api/requests.rs
tests/document_ops.rs
tests/group_ops.rs

see #64 
Adds need_rotation to `GroupCreateOpts`, allowing a group to be created with its private key marked for rotation

[#64] Adds needs_rotation to group creation

---

.travis.yml
CHANGELOG.md
src/group.rs
src/internal/group_api/mod.rs
src/internal/group_api/requests.rs
src/internal/user_api/mod.rs
src/internal/user_api/requests.rs
tests/document_ops.rs
tests/group_ops.rs
tests/user_ops.rs

- Made `GroupCreateOpts` contain a list of `UserIds` that should be added as members to the group. `group_create()` will fail if one of these `UserIds` cannot be found.
- Made `group_create()` return a `GroupCreateApiResponse` with a `try_into()` for a new `GroupCreateResult`. This result is similar to `GroupMetaResult` but includes a list of group admins and members.
- Added a test for adding members on create with the `members` list.
- Changed some tests to return Results and use `?` instead of `unwrap()` to get better error messages.
TODO:

Add members on group create

---

Cargo.toml
src/internal/document_api/mod.rs
src/internal/group_api/mod.rs
src/internal/rest.rs
src/internal/user_api/mod.rs
src/internal/user_api/requests.rs
src/lib.rs
src/user.rs

see #73 
Functions in the internal user API and request layer have been updated to use `async fn` instead of `impl Future` or `Box<dyn Future>`. Places outside of the user API that used user functions were not updated, but rather the new Futures were converted back to Futures 0.1. 
Note that `internal/user_api/mod.rs` and `internal/user_api/requests.rs` no longer import anything from the futures (0.1) crate.
The intent is to do the group_api, document_api, rest.rs in separate PRs.

[#73] Converts internal user api and user/requests to async fn

---

Cargo.toml

* For dev we do want to build our dependencies with optimization, but don't optimize ironoxide to keep the build times shorter.
* For test we want the same as dev.
* For release we want to fully optimize and try to remove code from the binary that we don't want.
This is identical to what we do in recrypt.

Adds build profiles for dev, test, release

---

CHANGELOG.md
Cargo.toml
src/document/mod.rs
src/group.rs
src/lib.rs
src/user.rs

[#84] Reuse tokio runtime for device auth'd SDK calls

---

.gitignore
CHANGELOG.md
Cargo.toml
src/internal/group_api/mod.rs
src/internal/group_api/requests.rs
src/internal/mod.rs
src/lib.rs
src/policy.rs
tests/group_ops.rs
tests/user_ops.rs

These changes are so that ironoxide-java can make its `initialize_and_rotate()` function include all groups that need rotation. 
I also noticed that the GroupUpdatePrivateKeyResult only returning `needs_rotation` makes sense when you're calling the function yourself one-by-one, but a `rotate_all()` will return a vector of results, so it should include the `GroupId` to relate the result to the group.

Implement rotate_all() for PrivateKeyRotationCheckResult

---

CHANGELOG.md
Cargo.toml
src/document/advanced.rs
src/document/mod.rs
src/group.rs
src/internal/document_api/mod.rs
src/lib.rs
src/user.rs
tests/common/mod.rs

- Update `bytes` to 0.5
- Update `reqwest` to 0.10
- Update `tokio` to 0.2.6
- Update `protobuf` to 2.10
- Standardized dependencies to use `~` to try to avoid our errors of misunderstanding `~` vs `^`

Update reqwest to 0.10.0

---

.travis.yml
CHANGELOG.md
Cargo.toml
benches/ironoxide_bench.rs
src/document/advanced.rs
src/document/mod.rs
src/group.rs
src/internal/group_api/requests.rs
src/lib.rs
src/user.rs
tests/common/mod.rs
tests/document_ops.rs
tests/group_ops.rs
tests/user_ops.rs

See #93 
We've decided that for now we are going to only provide an async API as this simplifies things given our internal API is async. If we need a sync API again in the future, it could be added in a separate name space, perhaps with a feature flag.
Obviously this is a huge breaking change, so we're merging this into a feature branch for now.

[#93] Make async api the default

---

CHANGELOG.md
src/internal/mod.rs
src/internal/user_api/mod.rs
src/internal/user_api/requests.rs
src/lib.rs
src/user.rs
tests/common/mod.rs
tests/group_ops.rs
tests/user_ops.rs

- Added `DeviceAddResult`, the new result of `generate_new_device()`
- This contains the same fields as `DeviceContext` with the addition of `device_id`, `name`, `created`, and `updated`.
- Added `From<DeviceAddResult> for DeviceContext` to give a `DeviceContext` for functions like `initialize()`
- Updated `DeviceAddResponse` to include new fields

Add DeviceAddResult

---

CHANGELOG.md
src/crypto/aes.rs
src/internal/document_api/mod.rs
tests/document_ops.rs

See #105 
Decryption had a check to explicitly disallow "empty" encrypted data. The check was also mistakenly disallowing 1 byte. Both restrictions were relaxed and tests introduced.

[#105] Fixes decryption of data with size 0 bytes and 1 byte

---

.travis.yml

Making sure that our issues with stable went away with 1.41.0

Use stable Rust on Travis

---

Cargo.toml

https://docs.rs/ironoxide isn't showing the `blocking` module. This should instruct docs.rs to use the `--all-features` flag.

Adds all-features to docs-rs build

---

CHANGELOG.md
Cargo.toml
benches/ironoxide_bench.rs
src/blocking.rs
src/document/advanced.rs
src/document/mod.rs
src/group.rs
src/internal/document_api/mod.rs
src/internal/mod.rs
src/lib.rs
src/user.rs
tests/blocking_ops.rs
tests/common/mod.rs
tests/document_ops.rs
tests/group_ops.rs
tests/user_ops.rs

See #19 
* Adds timeouts to all public API methods. Most timeouts use a top-level config set in `IronOxideConfig`. Some special cases allow for passing an optional timeout directly (`rotate_all`, `user_create`, `user_verify`, `generate_new_device`). Timeouts apply to both `IronOxide` and `BlockingIronOxide`
* Configs can now be set on `BlockingIronOxide`. Before, defaults were always used.
* Trying out a "open" struct for all config objects to allow for easier construction and access. If successful, we could use this idea in more in the SDK's public interface.
* Adds dependency on `tokio/rt-threaded` feature flag

[#19] Adds configurable timeouts to SDK methods

---

CHANGELOG.md
src/blocking.rs

Add function to BlockingIronOxide to clear policy cache. Simply calls `clear_policy_cache()` on its internal IronOxide.

Add clear_policy_cache() to BlockingIronOxide

---

src/internal/group_api/mod.rs
src/internal/group_api/requests.rs

Now that rotating the group's private key returns the group ID (currently only in dev), we can clean up our `From` impl to create a `GroupUpdatePrivateKeyResult` more cleanly.

Clean up GroupUpdatePrivateKeyResponse.into()

---

CHANGELOG.md
Cargo.toml
build.rs
src/crypto/aes.rs
src/document/mod.rs
src/group.rs
src/internal/document_api/mod.rs
src/internal/document_api/requests.rs
src/internal/group_api/mod.rs
src/internal/group_api/requests.rs
src/internal/mod.rs
src/internal/rest.rs
src/internal/user_api/mod.rs
src/internal/user_api/requests.rs
src/lib.rs
src/policy.rs
src/user.rs

This makes sure that Clone, Debug, Eq, Hash, and PartialEq are on all of our public types. 
Exceptions:
- IronOxide/BlockingIronOxide only have Debug, as parts of them like recrypt stop them from having others. 
- build.rs-generated structs like `ironoxide::proto::transform::PublicKey` only have Clone and PartialEq. I looked into finding a way to make it add others with no success. The full list is `EncryptedDekData`, `EncryptedDeks`, `PublicKey`, `UserOrGroup`, and the enum `UserOrGroup_oneof_userOrGroupId`.
TODO:

Add derives for Clone, Debug, Eq, Hash, and PartialEq for public types

---

.travis_scripts/cross-test.sh
Cargo.toml
src/blind_index.rs
src/blocking.rs
src/internal/mod.rs
src/lib.rs
src/search.rs
tests/search_ops.rs

Blind index

---

CHANGELOG.md
Cargo.toml

There is no downside here since we don't use any of the default features.
The motivation was that by default `publicsuffix` depends on `openssl-sys` for some functionality that we don't use. This causes problems in embedded environments that don't have openssl.
Now if you you depend `tls-rustls` in ironoxide, openssl is not needed at all compile time or runtime. It is still needed for integration tests because of our dependency on `frank_jwt`

Remove default features from publicsuffix

---

.travis.yml
.travis_scripts/cross-test.sh

This PR doesn't build or run tests, because
- #136 
- Test builds don't complete on i686 or x86_64; it just hangs trying to build.

Travis: Build several android architectures.

---

src/blocking.rs
src/document/mod.rs
src/internal/document_api/mod.rs
src/lib.rs
src/policy.rs
src/prelude.rs
tests/document_ops.rs

Trying to make ironoxide more easily understood from the docs alone. This PR focuses on the `document` functions and things related to them. 
I added examples for every `DocumentOps` function, which are compiled (but not run, because of async issues) when running `cargo test`, helping prove that they don't become out-of-date.
I need feedback on how the landing page of the docs site should flow. My current thought is that each section (Users, Groups, Documents), as well as a higher level (like Initialization) will provide a bare-bones example of the most important functions to get you up and running. A reader could start at the top and see how to initialize, create a user, create a group, and encrypt/decrypt a document right from that page. There will also be links to important functions …

Update DocumentOps docs

---

src/document/advanced.rs
src/document/mod.rs
src/internal/document_api/mod.rs
src/lib.rs
src/search.rs

Improve the documentation for all of the `document` module types. 
Also added some convenience `From/TryFrom` implementations we were missing (`DocumentName`, `UserOrGroup`)

Improve docs for document types

---

CHANGELOG.md
build.rs

This module was never intended to be used outside of the crate.

`proto` module is no longer `pub` in the crate

---

.github/workflows/ci.yaml
CHANGELOG.md
Cargo.toml
src/blocking.rs
src/internal.rs
src/internal/rest.rs
src/internal/user_api.rs
src/internal/user_api/requests.rs
src/lib.rs
src/user.rs
tests/common.rs
tests/user_ops.rs

Switched from `frank_jwt` to `jsonwebtoken`.
There already was an internal `Jwt` type, so re-purposed it and made it public. It validates that the jwt has the correct payload fields and an allowed algorithm. `user_create`, `user_verify`, and `generate_new_device` all use the new `Jwt` type instead of `&str`.
Also fixes:
- #162 
- #163

Add public Jwt type

---

CHANGELOG.md
Cargo.toml
src/internal/user_api.rs
src/lib.rs

Rust 1.46.0 seems to be generating longer type names, or perhaps a change in one of our dependencies is causing this - I'm not sure. 
A limit of 1670000 was suggested by the compiler (and seemed to be enough), so I just rounded up to 2000000 to give us some headroom in case things internal names get longer again.
Also bumped a couple of dependencies.
The crate builds without the `type_length_limit` directive on Rust `1.45.2`, but does not on `1.46.0` or `1.47.0-nightly (2d8a3b918 2020-08-26)`

Increase type_length_limit due to a change in Rust 1.46.0 

---

CHANGELOG.md
Cargo.toml
build.rs

This is a breaking change for any downstream consumers that also use rust-protobuf.

Upgrade to rust-protobuf 2.17

---

Cargo.toml

This will allow downstream consumers to choose their version of protobuf without causing build issues.
I realized this while looking at https://github.com/tikv/rust-prometheus/blob/master/Cargo.toml
I tested this by `git reset`ing logdriver to an old revision that used protobuf 2.14. It compiled file. It also compiled fine with a dependency of 2.17. 
There might still be problems in upgrading to newer version because we have custom `build.rs` logic for the proto generation, but at least cargo will be able to successfully select a version.
If we merge this, I think we can close https://github.com/IronCoreLabs/ironoxide/pull/188

Relax the semver requirement for protobuf

---

src/internal/rest.rs

Breaking change in patch bump :upside_down_face: 
For some reason, we were implementing `Display` using an export of `serde`, but apparently we weren't supposed to be able to import that (they renamed the module to `__private`). This change makes us implement `Display` in the standard way using `std::fmt::Display`, so the change is backwards compatible and we don't have to set a minimum version of `serde`.

Fix issue with serde 1.0.119

---

Cargo.toml

Changes from `~` requirements to no symbol (which is equivalent to `^` requirements). From the docs:
> Caret requirements allow SemVer compatible updates to a specified version. An update is allowed if the new version number  > does not modify the left-most non-zero digit in the major, minor, patch grouping. In this case, if we ran cargo update -p time,  cargo should update us to version 0.1.13 if it is the latest 0.1.z release, but would not update us to 0.2.0. If instead we had specified the version string as ^1.0, cargo should update to 1.1 if it is the latest 1.y release, but not 2.0. The version 0.0.x is not considered compatible with any other version.
This compatibility convention is different from SemVer in the way it treats versions before 1.0.0. While SemVer says there is no …

Change all dependencies to default upgrade requirements

---

CHANGELOG.md
Cargo.toml
src/internal/rest.rs

As discovered in #231, we were only using publicsuffix for the `IntoUrl` trait. Instead, we can just call `url::Url::parse` directly ourselves.

Remove dependency on publicsuffix

---

src/crypto/transform.rs
src/document.rs
src/internal.rs
src/internal/document_api.rs
src/internal/document_api/requests.rs
src/internal/group_api.rs
src/internal/group_api/requests.rs
src/internal/rest.rs
src/internal/user_api.rs
src/internal/user_api/requests.rs
src/lib.rs

A few lints were just silenced: too many arguments, complex return type, and large enum size difference.
This did lead to some changes in our public API, so we'll have to decide if we're okay with that (changing anywhere we take `&Vec<_>` to `&[_]`).
With this satisfied, we could consider adding the clippy workflow to this repo's CI

Satisfy clippy

---

.github/workflows/ci.yaml
CHANGELOG.md
Cargo.toml
src/blocking.rs

- Update to recrypt 0.13
- Update to rand 0.8
- Update to rand_chacha 0.3
- Update to ironcore-search-helpers 0.2

Rust 2021, dependency upgrades

---

CHANGELOG.md
Cargo.toml
src/internal.rs
src/internal/document_api.rs
src/internal/document_api/requests.rs
src/internal/group_api.rs
src/internal/group_api/requests.rs
src/internal/rest.rs
src/internal/serde_rfc3339.rs
src/internal/user_api.rs
src/internal/user_api/requests.rs

Closes #244 #245 
This change should not have any semantic meaning and is being done to address RUSTSEC-2020-0071 (see #244) and RUSTSEC-20200159 (see #245).
This is a breaking API change because some result types include create/updated timestamps. Consumers of the library will need to add a direct dependency on `time`. Note that `chrono` already uses `time` internally, so this change should not bloat transitive dependencies.
For those needing serialization support of  `OffsetDateTime` timestamps, the `time` crate offers this support with the `serde` feature flag.
One small point of friction here is rfc3339 support. `time` has this support on [a branch](https://github.com/time-rs/time/issues/387) that is blocked on a rust feature hitting stable, so I copied in a few lines of code from …

Removes `chrono` and  usages  of `DateTime<Utc>` and replaces them with`time::OffsetDateTime`

---

CHANGELOG.md
benches/ironoxide_bench.rs
examples/decrypting.rs
examples/enc-search-sample.rs
examples/encrypting.rs
src/blocking.rs
src/crypto/aes.rs
src/document.rs
src/document/advanced.rs
src/internal/document_api.rs
src/lib.rs
src/search.rs
tests/blocking_ops.rs
tests/document_ops.rs
tests/group_ops.rs
tests/user_ops.rs

PR really has 2 parts, so I broke them into 2 commits you can view separately. I think we should definitely keep 1, but we could decide to not do 2.
1. `crypto::aes::encrypt` now takes `Vec<u8>` plaintext instead of `&[u8]`. The call sites were all already doing `&plaintext.to_vec()`, so they had owned data. And now we don't have to `.to_owned()` when encrypting.
2. Changes our public functions like `document_encrypt()` to take `Vec<u8>` instead of `&[u8]`. Since this is public this would be a breaking change. But essentially if we need owned data, we should take owned data (instead of just internally cloning with `.to_vec()`). It'll instead be up to the caller whether or not they need to clone their data (and I think they frequently won't need to be using their unencrypted_data again …

Don't clone plaintext on aes encryption

---

.github/workflows/daily.yaml

We're inconsistent with this across repos, but this makes the triggers match our others. This will make this no longer run on PRs (making it look like CI is failing when it's just a previously-known dependency deprecation).

Only run security audit on schedule

---

.github/workflows/daily.yaml

This is obsoleted by Dependabot.

Remove the daily security audit.

---

.github/workflows/daily.yaml

Leaving the cache directive, commented out, with a comment to prevent somebody from re-adding it.

Don't use the Rust cache for daily builds.

---

.github/workflows/ci.yaml
Cargo.toml
flake.lock
rust-toolchain.toml

The latest version of our transitive dependency `clap` requires Rust 1.74.0 or greater.
https://github.com/IronCoreLabs/ironoxide/actions/runs/8065999588/job/22033074280#step:8:205

Bump MSRV to 1.74.0

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
CHANGELOG.md
Cargo.toml
benches/ironoxide_bench.rs
flake.lock
rust-toolchain.toml
src/document.rs
src/document/advanced.rs
src/group.rs
src/internal/user_api.rs
src/internal/user_api/requests.rs
src/lib.rs
src/policy.rs
src/prelude.rs
src/search.rs
src/user.rs

- Removes async-trait to improve docs
- Adds release workflow
- Bumps dependencies
- Fixes an issue with running benchmarks
- Exports `itertools::EitherOrBoth` so upgrades aren't automatically a breaking change

Prepare 3.0

---

src/blocking.rs
src/internal.rs
src/internal/rest.rs
src/lib.rs
src/user.rs
tests/blocking_ops.rs

Opening this as a PR to see about test failures.

Reuse the Client in all cases

---

.github/workflows/ci.yaml
Cargo.toml
flake.lock
rust-toolchain.toml
src/lib.rs

Transitive dependency
home@0.5.11 requires rustc 1.81

Update MSRV to 1.81
